# Generated by Django 5.2.5 on 2025-08-26 11:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, verbose_name='Partner Email')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=64, verbose_name='Customer First Name')),
                ('customer_last_name', models.CharField(max_length=64, verbose_name='Customer Last Name')),
                ('customer_company', models.CharField(max_length=64, verbose_name="Customer's Company Name")),
                ('customer_email', models.EmailField(max_length=254, unique=True, verbose_name='Customer Email')),
                ('customer_phone_number', models.CharField(max_length=20)),
                ('customer_city', models.CharField(max_length=64)),
                ('customer_country', models.CharField(max_length=64)),
                ('customer_address', models.TextField()),
                ('customer_partner_service', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='portal.partnerservice')),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateField(auto_now_add=True)),
                ('claim_last_modified', models.DateField(auto_now=True)),
                ('claim_type', models.CharField(choices=[('RP', 'Repair'), ('BT', 'Bulletin')], default='RP', max_length=2)),
                ('vehicle_driver_name', models.CharField(max_length=64)),
                ('vehicle_driver_phone', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('CS', 'CurtainSider'), ('PF', 'Platform'), ('CC', 'ContainerChassis'), ('SB', 'SwapBody'), ('RF', 'Reefer'), ('BX', 'Box'), ('SI', 'Silo'), ('TK', 'Tanker'), ('LB', 'LowBed'), ('TP', 'Tipper'), ('OT', 'Other')], default='OT', max_length=2)),
                ('vehicle_defect_date', models.DateField(default=datetime.date(2025, 8, 26))),
                ('vehicle_chassis_number', models.CharField(max_length=64)),
                ('vehicle_registration_date', models.DateField(default=datetime.date(2025, 8, 26))),
                ('vehicle_kilometer', models.IntegerField()),
                ('defect_category', models.TextField()),
                ('claim_status', models.BooleanField(default=False)),
                ('defect_description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='portal.customer')),
            ],
        ),
    ]
