# Generated by Django 5.2.5 on 2025-08-27 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyclaim',
            name='vehicle_defect_date',
            field=models.DateField(default=datetime.date(2025, 8, 27)),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='vehicle_registration_date',
            field=models.DateField(default=datetime.date(2025, 8, 27)),
        ),
    ]
