# Generated by Django 5.2.5 on 2025-08-28 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_warrantyclaim_vehicle_defect_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Customer Email'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='vehicle_defect_date',
            field=models.DateField(default=datetime.date(2025, 8, 28)),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='vehicle_registration_date',
            field=models.DateField(default=datetime.date(2025, 8, 28)),
        ),
    ]
