# Generated by Django 5.2.5 on 2025-08-29 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_customer_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_partner_service',
            new_name='partner_service',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_phone_number',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='claim_type',
            field=models.CharField(choices=[('RP', 'Repair'), ('BT', 'Bulletin')], default='RP', max_length=3),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='vehicle_defect_date',
            field=models.DateField(default=datetime.date(2025, 8, 29)),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='vehicle_registration_date',
            field=models.DateField(default=datetime.date(2025, 8, 29)),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='vehicle_type',
            field=models.CharField(choices=[('CS', 'Curtain Sider'), ('PF', 'Platform'), ('CC', 'Container Chassis'), ('SB', 'Swap Body'), ('RF', 'Reefer'), ('BX', 'Box'), ('SI', 'Silo'), ('TK', 'Tanker'), ('LB', 'Low-Bed'), ('TP', 'Tipper'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
