# Generated by Django 5.2.5 on 2025-08-29 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_customer_address_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyclaim',
            name='partner_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='portal.partnerservice'),
        ),
    ]
