# Generated by Django 5.2.5 on 2025-08-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_warrantyclaim_partner_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyclaim',
            name='partner_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='portal.partnerservice'),
        ),
    ]
