# Generated by Django 5.2.5 on 2025-09-01 05:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_warrantyclaim_createdby'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyclaim',
            name='claim_status',
            field=models.CharField(choices=[('NW', 'New'), ('RV', 'Revised'), ('NR', 'Needs Revise'), ('AC', 'Accepted'), ('RJ', 'Rejected'), ('CP', 'Completed')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='vehicle_defect_date',
            field=models.DateField(default=datetime.date(2025, 9, 1)),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='vehicle_registration_date',
            field=models.DateField(default=datetime.date(2025, 9, 1)),
        ),
    ]
