# Generated by Django 5.2.5 on 2025-09-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_warrantyclaim_claim_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warrantyclaim',
            old_name='claim_status',
            new_name='status',
        ),
    ]
