# Generated by Django 5.2.5 on 2025-09-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_sparepart_rename_createdby_warrantyclaim_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyclaim',
            name='claim_type',
            field=models.CharField(choices=[('RP', 'Repair'), ('BT', 'Bulletin')], default='RP', max_length=2),
        ),
    ]
