# Generated by Django 5.2.5 on 2025-09-01 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_warrantyclaim_claim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyclaim',
            name='vehicle_defect_date',
            field=models.DateField(default=datetime.date(2025, 9, 2)),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='vehicle_registration_date',
            field=models.DateField(default=datetime.date(2025, 9, 2)),
        ),
    ]
