# Generated by Django 5.2.5 on 2025-09-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_warrantyclaim_vehicle_defect_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='price',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='price_gbp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='price_try',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='stock_code',
            field=models.CharField(db_index=True, default=0, max_length=64, unique=True, verbose_name='Stock Code'),
        ),
    ]
