# Generated by Django 5.2.5 on 2025-09-02 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_remove_sparepart_price_sparepart_price_eur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyclaim',
            name='vehicle_chassis_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ClaimSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=64, verbose_name='Stock Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField()),
                ('approved_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='portal.warrantyclaim')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_spareparts', to='portal.sparepart')),
            ],
            options={
                'unique_together': {('claim', 'spare_part')},
            },
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='spare_parts',
            field=models.ManyToManyField(blank=True, related_name='claims', through='portal.ClaimSparePart', to='portal.sparepart'),
        ),
    ]
