# Generated by Django 5.2 on 2025-09-02
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_warrantyclaim_vehicle_chassis_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsparepart',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('TRY', 'Turkish Lira')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='claimsparepart',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
