# Generated by Django 5.2.5 on 2025-08-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerfields',
            old_name='partner_service',
            new_name='partner_service_id',
        ),
    ]
