# Generated by Django 5.2.5 on 2025-08-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_partner_service_partnerfields_partner_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerfields',
            old_name='partner_service_id',
            new_name='partner_service',
        ),
    ]
