# Generated by Django 5.2.5 on 2025-09-01 22:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_partner_service_id_partnerfields_partner_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', users.models.PartnerAdminManager()),
            ],
        ),
        migrations.CreateModel(
            name='SSHAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', users.models.SSHAdminManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PARTNER', 'Partner'), ('PARTNER_ADMIN', 'Partner Admin'), ('SSH', 'SSH'), ('SSH_ADMIN', 'SSH Admin')], default='PARTNER', max_length=20, verbose_name='Type'),
        ),
    ]
